=== YuraLukyanov/Group3_lab2/container/src/test/resources/beans_rules.xsd
<xsd:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <!-- Root element -->
    <xsd:element name="beans" type="beansType"/>


    <!-- Beans elements -->
    <xsd:complexType name="beansType">
        <xsd:sequence>
            <xsd:element name="bean" type="beanType" maxOccurs="unbounded"
                         minOccurs="1"/>
        </xsd:sequence>
    </xsd:complexType>



    <xsd:complexType name="beanType">
        <xsd:sequence>
            <xsd:element name="property" type="propertyType"
                         maxOccurs="unbounded"
                         minOccurs="0"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:ID" use="required"/>
        <xsd:attribute name="class" type="xsd:string" use="required"/>
    </xsd:complexType>


    <xsd:complexType name="propertyType">
        <xsd:sequence>
            <xsd:element name="property" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:choice minOccurs="0" maxOccurs="1">
                <xsd:element name="ref"/>
                <xsd:element name="value"/>
                <xsd:any namespace="##other" processContents="strict"/>
            </xsd:choice>
        </xsd:sequence>
        <xsd:attribute name="name" type="xsd:string" use="required"/>
        <xsd:attribute name="ref" type="xsd:string"/>
        <xsd:attribute name="value" type="xsd:string"/>
    </xsd:complexType>


</xsd:schema>

=== YuraLukyanov/Group3_lab2/container/src/main/resources/test_beans.xml
<?xml version="1.0" encoding="UTF-8" ?>

<!--old beans-->
<beans  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="beans_rules.xsd">
    <bean id="someProduct" class="controller.test_services.Product"/>
   <bean id="basket" class="controller.test_services.Basket">
        <property name="position" value="2"/>
        <property name="addProduct" ref="testAddProduct"/>
    </bean>

    <bean id="testAddProduct" class="controller.test_services.TestAddProduct">
        <property name="product" ref="someProduct1"/>
    </bean>

    <bean id="someProduct1" class="controller.test_services.Product">
        <property name="id" value="555"/>
        <property name="type" value="computer"/>
    </bean>
    <!--_____________________________________________-->
    <bean id="ProductManager" class="controller.test_services.ProductManager"/>


</beans>
